### ISSUE TITLE
Homepage in Safari

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#105]
Using Safari, in the menu bar, “Contribute” “Contact Us” and “Search” are overlapping

**Comment by SourenP** [comment]
seems to have been fixed

**Comment by Hasmig** [comment]
It still does it for me. Attached is a screenshot.
![screen shot 2016-03-23 at 8 50 08 pm](https://cloud.githubusercontent.com/assets/11155569/14007953/f6af8b26-f138-11e5-91ad-fca79c3f1c06.png)
