### ISSUE TITLE
Edit and re-arrange titles in Teaching Guides

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#111]
I added the iWitness lesson plan to Teaching Guides, but I don't want it at the top of the list.   I also would like to change the look of the title, but I don't know how to change fonts/colors for the titles.

**Comment by GenEdProject** [comment]
This is now fixed. There was a bug in our templating logic.

**Comment by Hasmig** [comment]
The same problem exists with the Books page and the Videos page. I haven't checked other pages yet, but there could be the same problem. I'd also like to change the style of the titles sometimes. Is there a way to do that?

**Comment by GenEdProject** [comment]
I fixed it for the other pages.. good catch.

**Comment by GenEdProject** [comment]
I don't think there's an easy way for *you* to change the style of the titles. If you come up with a style you'd like to use everywhere, I can redefine what the title looks like across the board.
