### ISSUE TITLE
Press Release problem

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#112]
I created this press release: http://teachgen.hayg.info/1248-2/?preview=true&preview_id=1248&preview_nonce=2ac349e57a&post_format=image

But, there are problems:
1. I can't figure out how to create a double headline/title, i.e. a headline and a smaller sub-headline.  To resolve it, I put the headline in the title window, and the sub-headline in the body of the text. It looks OK on the press release page, but it doesn't look right on homepage, where the headline is small and the sub-headline is big, and only the top of the photo appears. On the homepage, I don't know how to get the press release to hyperlink to the full release.

2. I'm having problem formatting the text of all my posts. I can't figure out how to modify font sizes, styles. When I try to enlarge the font on one phrase or subhead by using "Heading" in the font window, the entire paragraph will enlarge.

3. I don't know how to add the summary of my press release onto the GenEd News page: http://teachgen.hayg.info/gened-news/

4. The GenEd News page should have images from the press releases next to each one.

**Comment by copacetic** [comment]
The key for not having the whole post show up is to insert a 'Read more' button into the text. That way only the post up to the 'Read more' will get shown on the GenEd News page.

We can improve the page to allow for an image for each post. The formatting will be trickier. If you ever find yourself getting really desperate, you can always write it in Word and copy paste in. It should automagically turn it into HTML for you.

**Comment by Hasmig** [comment]
I tried formatting something in a word document and then copy and pasting it into a press release post in Wordpress, but the text just reverted to the default font size and style.  I'm really surprised that the text editing page in Wordpress includes functions keys for bold, italic, text color, etc, but no font sizes or styles.

**Comment by copacetic** [comment]
I think i fixed this. Now you should have a much richer editor which can set font size and family. Beware that this is a dangerous tool that can lead to having inconsistent typography across the site

**Comment by Hasmig** [comment]
OK. Right, I guess we have to be careful when we paste text from elsewhere into Wordpress. In fact, I don't see that it tells me which font is in use.  When I go to Font Families and Font Sizes, nothing is checked or highlighted in any way to tell me what font and size I'm using.
