### ISSUE TITLE
New York Times book

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#117]
In Teaching Guides, I combined the New York Times book entry with the lesson plan that goes with it (even though teachers don't have to have the book to use the lesson plan.) We need to include an option to order the book from us.

Also, the NYT book is also included on the Books page, but we need to indicate that we sell it and include a button to purchase it.

**Comment by copacetic** [comment]
Hmm, I just took all the for-sale items from the old site. I don't see it listed:
http://www.teachgenocide.com/orderform/

If we want to add it, I need a cost, a description, and ideally an image for it.

**Comment by Hasmig** [comment]
It's weird. Raffi put it in the left column on the following page with a ink to an order form for $25: http://www.teachgenocide.com/newsaccounts/index.htm

There's an image of the cover of the book (the new edition has a red cover, not blue) in the photo gallery of the Wordpress admin site: http://teachgen.hayg.info/wp-admin/upload.php?item=1126

**Comment by copacetic** [comment]
Ok, updated!

**Comment by Hasmig** [comment]
Thanks.
