### ISSUE TITLE
Wrong link 

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#118]
On the Teaching Guides page and individual page for "Human Rights and Genocide: A Case Study of the First Modern Genocide of the 20th Century," the titles link to a map, instead of the lesson plan binder, as they should.

I'm having all kinds of formatting problems on the text of that page, getting the line spaces and bullet points right.

I'd like to work towards allow teachers to either to order the entire binder, download the entire binder, or download some of the individual sections of the binder. Let me know if you need me to send you the entire binder PDF and/or the individual sections/lessons I'd like to offer for download.

**Comment by copacetic** [comment]
hi hasmig, could you send me the pdf you want the download to link to?

**Comment by Hasmig** [comment]
[LessonPlans-Case Study First Modern Genocide 20th Century 4th Ed- Complete Binder (209 pgs).pdf](https://github.com/GenEdProject/TeachGenocideSite/files/50468/LessonPlans-Case.Study.First.Modern.Genocide.20th.Century.4th.Ed-.Complete.Binder.209.pgs.pdf)

**Comment by copacetic** [comment]
Thank you. Fixed.

**Comment by Hasmig** [comment]
Can we also put an "Add to Cart" on:
"Human Rights and Genocide..."

I'm wondering whether "Add to Cart" and "Download" will be confusing to people; I wonder if they're think that downloading also costs money...? Should we write above these buttons something like, "Hard copies available for purchase, $25.  Electronic copies can be downloaded free of charge."
