### ISSUE TITLE
=An Armenian Journey: From Despair to Hope

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#119]
On the Teaching Guides page, we'll need to add "Add to Cart" to purchase the teaching guide and DVD.

Although I just sent you a description of this guide and video, I realize there's already a description on this page, which is fine.

Maybe we need to add at the end, above "Add to Cart": 
Watch the 12-minute documentary "An Armenian Journey" on YouTube (hyperlinked)
The teaching guide and DVD can be purchased for $25; The resource guide can be downloaded free of charge.

**Comment by copacetic** [comment]
This should be updated: http://teachgen.hayg.info/teaching_guides/an-armenian-journey-from-despair-to-hope-in-rhode-island/
