### ISSUE TITLE
AG Memorial Photo alignment 

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#139]
On the Armenian Genocide Memorial page, I can't figure out how to freely lay out the photos. I've tried using the no-alignment option in the toolbar or in the box appears above the selected photo, or in the edit function of the box above photo.

**Comment by SourenP** [comment]
It's because the page is 990px wide which doesn't show when you're editing but is what the site looks like live. I played around with it a bit and put up better quality images. Let me know what you think.

**Comment by Hasmig** [comment]
That looks 100 times better! Thank you! What was your process? Did you just keep estimating and changing the sizes of the images, until they showed up in the right position when viewed on the site page?

**Comment by SourenP** [comment]
Yup, well I put in the numbers knowing that the width was 990px.
