### ISSUE TITLE
Need banner photos for pages

### ISSUE THREAD

**Issue by copacetic** [GenEdProject/TeachGenocideSite#39]
Contacted Melani about this.

**Comment by copacetic** [comment]
Added a lame one for 'Contact Us.'

**Comment by SourenP** [comment]
We need to figure out what size we want these to be.
If the screen is larger than the banner then it repeats.
So maybe having the original picture be 2000px is a good 'max'.

**Comment by SourenP** [comment]
Btw we currenly have three:

March
Books
People

**Comment by SourenP** [comment]
Duplicate issue: https://github.com/GenEdProject/TeachGenocideSite/issues/62
