### ISSUE TITLE
State Educational Requirements

### ISSUE THREAD

**Issue by copacetic** [GenEdProject/TeachGenocideSite#41]
Make it. http://teachgen.hayg.info/resources/state-educational-requirements/

**Comment by SourenP** [comment]
![screenshot from 2015-03-02 02 15 40](https://cloud.githubusercontent.com/assets/3184499/6436702/0aaadaba-c082-11e4-8398-a1e7f3b06dc9.png)

**Comment by copacetic** [comment]
This is done. http://teachgen.hayg.info/resources/state-educational-requirements/
