### ISSUE TITLE
Add email list registration

### ISSUE THREAD

**Issue by copacetic** [GenEdProject/TeachGenocideSite#46]

**Comment by GenEdProject** [comment]
https://wordpress.org/plugins/mail-subscribe-list/

**Comment by GenEdProject** [comment]
@copacetic added an email registration form here: http://teachgen.hayg.info/about-us/

I don't want it bolding everything though. That's a side effect of me using the <table> tag to align things.

**Comment by GenEdProject** [comment]
http://teachgen.hayg.info/register/for-educators/
http://teachgen.hayg.info/register/for-supporters/

These plug directly into mailchimp! No need for manual intervention.
