### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#51]
The layout is looking odd - Sections are moving around in unexpected ways when I adjust the size of the window, with big white spaces on the upper right and lower left quadrants of the bottom half of the page. I remember discussing whether to create a fixed width site or responsive (or fluid? elastic?), but I thought we had settled on fixed width.

**Comment by SourenP** [comment]
We are now using a new design that uses fixed width. 
All the content is centered in a 990px box and all panels now have a fixed size.

We're going to try to make everything a bit less 'fat'. Smaller arrows, slimmer titles etc.
But it should look good after that.

**Comment by copacetic** [comment]
Awesome stuff Souren. Good job! Now we need to make it mobile friendly
