### ISSUE TITLE
Homepage colors

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#52]
I'd like to use the colors Melani created. But, we've also asked our original logo designer to create an updated version. I will send you the web version of the logo asap.  In the meantime, to give you an idea of the new logo, color, and design elements, I'm attaching screenshots of the two sides of our new publicity postcard (this site doesn't accept PDFs).
![screen shot 2015-02-22 at 11 16 29 pm](https://cloud.githubusercontent.com/assets/11155569/6324063/f1f3be2c-bae8-11e4-919c-8a0c014f6dcc.png)
![screen shot 2015-02-22 at 11 16 09 pm](https://cloud.githubusercontent.com/assets/11155569/6324062/f1f393c0-bae8-11e4-9ef3-e6e6b19a14a5.png)

**Comment by copacetic** [comment]
The colors are very different from the mockups. We're switching to the mockup colors, definitely. Maybe Melani would best know how to reconcile them.

**Comment by Hasmig** [comment]
Reconcile what with what?

**Comment by SourenP** [comment]
I like this green color. Should we give it a try and see how it looks?

**Comment by Hasmig** [comment]
I've told Melani about fitting the new logo/publicity colors with the colors she created for the site. So, I suggest not spending your time on that right now, until Melani takes a look.
I'm waiting to get the logo design in a web-usuable version.

**Comment by copacetic** [comment]
@Hasmig That's what I meant by reconcile. Reconcile the new logo colors with those of the mockup so far.

**Comment by Hasmig** [comment]
I'll talk to Melani tomorrow.

**Comment by Hasmig** [comment]
![gep logo 4c](https://cloud.githubusercontent.com/assets/11155569/8028482/b32ca56e-0d63-11e5-825b-104da69ab839.jpg)

**Comment by SourenP** [comment]
Can you give us a png of this logo which has the background as transparent.
See the site to understand why this is needed.
