### ISSUE TITLE
Homepage video box

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#53]
We have a new 4-min. publicity video, and I'd like to have a box on the homepage for it.

**Comment by SourenP** [comment]
I put it there, but I'm not sure if it looks great: http://teachgen.hayg.info/

**Comment by Hasmig** [comment]
I'm not sure either. Do we have the option to switch from the video to a recent news release? Any other ideas for prominently displaying the video on the homepage?

**Comment by SourenP** [comment]
That box displays the most recent new release.
To put the video there, all I did was make a new news release (using wordpress - no code) and attached the video in it.

Perhaps displaying it very large as the banner? This would mean we wouldn't have "Learning the Past, Building the Future", and the news release would be moved down.

**Comment by Hasmig** [comment]
Hi Souren,

Let's leave the video in the box as you have it, even though, as you noted, it may not be the best. We'll switch it out with each new press release. I don't think it'll look that great running across the whole banner.
Can you give me your email address?
Did you get the logos and the new website colors design I sent last night. I'm seeing a version of those emails in my Drafts folder, so I wasn't sure if you actually go them.

**Comment by SourenP** [comment]
I didn't
My email is souren@papazian.info
