### ISSUE TITLE
Background tab and Resources tab drop down menus

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#54]
The "Hitler and the Armenian Genocide" title and the "Armenian Genocide Memorial Monument" title in the drop down menu under the Background tab don't read well, because it looks like they're broken up into two titles, i.e. "Hitler and the Armenian"  and "Genocide"  and "Armenian Genocide" and "Memorial Monument."  The same problem occurs with the "State Education Requirements" title under the Resources tab

**Comment by copacetic** [comment]
We could try making the dropdown wider

**Comment by SourenP** [comment]
Made it wider

**Comment by Hasmig** [comment]
On my laptop, "Genocide Memorial" and "Monument" are on two separate lines in the drop down, and on my desktop computer, they're on the same line.  On both computers, "Hitler and the Armenian" and "Genocide" are on different lines. I don't like the fact that it looks like those are two different titles. Can we either make the dropdown wide enough to accommodate the whole titles on large and small screens, or change the way it looks when the titles are broken up, so that it's clear that the words are part of the same title (I'm not sure how to do that, though)?
