### ISSUE TITLE
No need for "video" icon

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#55]
I don't think this icon on the Videos page is necessary, and I don't think it fits our general style

![screen shot 2015-02-22 at 11 31 54 pm](https://cloud.githubusercontent.com/assets/11155569/6324183/21258b92-baeb-11e4-88bc-83d7df4cafdd.png)

**Comment by SourenP** [comment]
These are placeholders, we're waiting on Melani for the real icons. 
The good thing is that these are edited through the wordpress admin page, so it can be changed very easily and by anyone (no code needed)

**Comment by Hasmig** [comment]
Melani isn't working on icons, as far as I know.  Unfortunately, she doesn't have much time to work on this anymore.  I may see if our logo designer would be able to help in this regard, but she's going to have a baby in a month, so that's not a reliable situation either.

**Comment by SourenP** [comment]
To be honest I think we don't even need icons. 
Let me modify the site not to have icons and let me know how you think it looks.

**Comment by SourenP** [comment]
How does that look:
http://teachgen.hayg.info/resources/books/

**Comment by copacetic** [comment]
I like that the dividers go all the way across. I think the section headers should have a more significant font styling though. And the dividers could maybe benefit from being a bit bolder

**Comment by Hasmig** [comment]
I agree that the section headers should have strong styling and the dividers bolder. On the books page, the order of sections should follow that of our current site, as I mentioned earlier. On the Videos page, the headers should specify what type of videos in each section.  Also, as I had mentioned early on, we'd like to embed a number of our YouTube videos on that page, or at least have a prominent announcement there that teachers can access short, classroom-ready videos on our YouTube page. But since there are also other non-classroom videos on our YT page, I'd prefer to embed a few of the key videos, and indicate that there are also others on YT.

**Comment by SourenP** [comment]
moved this issue to https://github.com/GenEdProject/TeachGenocideSite/issues/75
