### ISSUE TITLE
Larger images of video covers

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#56]
I'd like to see larger cover images of the videos

**Comment by copacetic** [comment]
We would need to be provided those images

**Comment by Hasmig** [comment]
I can try to get those, but not immediately. In the meantime, can we at least include the entire image of the video covers, not a cropped square image?

**Comment by copacetic** [comment]
We made this change. The result is that the videos float at different sizes in the right column:
http://teachgen.hayg.info/resources/videos/
