### ISSUE TITLE
Books page columns

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#57]
I think it would be better to have one column, instead of two columns that are uneven.  I'd prefer a layout more like the Videos page, or grouped in bunches like our current website, with hyperlinks to "more" info for each title. The order of the groups should be the same as the order here: http://www.teachgenocide.com/books/index.htm

**Comment by SourenP** [comment]
Changed template to "list left" like Videos page and fixed order.
Making new issue about images being stretched.
