### ISSUE TITLE
Survivor Accounts page

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#58]
On my computer, the left side of the page is blank/white, and the right side has Racoubian's quote. His photo is stretched (i.e. incorrect aspect ratio). We should put his quote in quotation marks and possibly italics.

**Comment by SourenP** [comment]
This is a placeholder, we have yet to design that page.

**Comment by SourenP** [comment]
http://teachgen.hayg.info/resources/survivor-accounts/

How does this look?
Maybe we should make all the images the same size.

**Comment by SourenP** [comment]
Made them all the same size.
I think the page is almost complete.

**Comment by Hasmig** [comment]
Souren - Sorry for the long delay in looking at this. I wish you had reminded me, because it slipped through the cracks when I was cramming too much work in, before heading off to Turkey.  I hope you haven't been waiting for my answers to continue working.  Anyway, I think the survivor accounts page looks alright. What if we made the photos larger and wrapped the text around them?

**Comment by SourenP** [comment]
I can't make the photos larger, that's the resolution we have. 
I think it looks fine.
Regarding the wrapping: we tried that and this looked much better!

**Comment by Hasmig** [comment]
I can easily get higher resolution images from the photographer, if you think it would be better
