### ISSUE TITLE
Documents and Maps layout

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#61]
The page looks a bit dull, because there are no images. I think it would be good to include an image of the first (sometimes the only) document of each title, and hyperlink it to a larger image or the full set of documents associated with the title.

**Comment by SourenP** [comment]
Here is the new layout according that matches Melani's mockup: http://teachgen.hayg.info/resources/documents-and-maps/
(the image on the side can be set to anything by you guys. You can even put several + text)
Let me know what you think.

**Comment by Hasmig** [comment]
I think that looks good if we can populate the right side with interesting images, as you said.
