### ISSUE TITLE
Tab function

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#65]
Sometimes when I put my cursor on one of the tabs, like "Resources," the drop down menu is cut short. It happens intermittently.

**Comment by SourenP** [comment]
Has this happened again? 
I've never noticed this.

**Comment by Hasmig** [comment]
Here’s our new logos. The main one is the green round one.

**Comment by Hasmig** [comment]
Dear Souren,

Unfortunately, Melanie worked on the web design colors, before we asked our logo designer to make new designs for our logo and a few new materials we printed recently (our booth banner, publicity postcards, event flyers, and our logo).  Now, I’m concerned that the website colors don’t jive with the logo and other publicity colors. So, Arsineh, who did our logo work, did a quick attempt to  come up with an easily programmable color scheme, attached.  You can read what she says about it, below. The problem is, I don’t think it’s as attractive as Melani’s colors.

Roxanne

Begin forwarded message:

> From: Arsineh Khachikian <arskhach@gmail.com>
> Subject: Re: GenEd website InDesign files
> Date: March 6, 2015 at 6:10:11 AM PST
> To: Makasdjian Roxanne <makas@pacbell.net>
> 
> Hi Roxanne,
> 
> Ok, I did a couple adjustments that would keep this really simple and still reflect the new look of GenEd. From a programmers perspective, it's a matter of changing maybe 3-4 web color codes in the CSS and the header image. That's it. Let me know if you think this will be sufficient for your needs and help push the process along.
> 
> Best,
> Arsineh
> 
> 
> 
> 
> Arsineh Khachikian | CREATIVE DIRECTOR
> ARKREATIVE DESIGN STUDIO
> M + 1 202 230 6566 | ARSKHACH@GMAIL.COM
> 
> www.arskhach.com
> 
> 
> On Thu, Mar 5, 2015 at 3:12 AM, Makasdjian Roxanne <makas@pacbell.net> wrote:
> Hi Arsineh,
> 
> Attached are inDesign files for our website design that Melani (my workmate) worked on. As we discussed, I’d love your thoughts on whether it’s possible to resolve the inconsistency between the website colors and design and our new publicity colors and designs you’ve created.
> 
> Sincerely,
> Roxanne
> 
> Begin forwarded message:
> 
> >
> 
> 
> 
>

**Comment by SourenP** [comment]
This isn't a problem, it shouldn't be difficult to change the colors.
But I didn't receive the attachment in Arsineh's email (since we're using github)
Could you forward that email to souren@papazian.info

Thanks
