### ISSUE TITLE
U.S. Ambassador to Turkey Page

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#67]
The U.S. Ambassador to Turkey Page should include this introduction, and the excerpt should have quotation marks around it.
Page Sub-heading:  Henry Morgenthau, Sr. - American Ambassador to Turkey, 1913-1916.

Ambassador Morgenthau's Story is one of the most insightful and compelling accounts of what became a recurring horror during the 20th century: ethnic cleansing and genocide. While he served as the U.S. ambassador to the Ottoman Empire under Woodrow Wilson from 1913 to 1916, Henry Morgenthau witnessed the rise of a new nationalism in Turkey, one that declared "Turkey for the Turks." He grew alarmed as he received reports from missionaries and consuls in the interior of Turkey that described deportation and massacre of the Armenians. The ambassador beseeched the U.S. government to intervene, but it refrained, leaving Morgenthau without official leverage. His recourse was to appeal personally to the consciences of Ottoman rulers and their German allies; when that failed, he drew international media attention to the genocide and spearheaded private relief efforts.

Below are excerpts from Ambassador Morgenthau's Story, published in 1918:

**Comment by SourenP** [comment]
Fixed.

**Comment by Hasmig** [comment]
Are you planning on laying out the page better later, i.e. formatting the titles, font sizes, etc, adding Morgenthau's photo...?
