### ISSUE TITLE
External Websites Page layout

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#69]
I think the page would be easier to follow if the websites were in one column, separated into groups using boxes or other design devise, instead of in two columns.

**Comment by SourenP** [comment]
What do you think of the new layout?

**Comment by Hasmig** [comment]
It's good, but I think it would be good to somehow strengthen the look of the headlinngs, so they stand out more. Also, maybe we should include some kind of logo/image next to each of the sites. Can we grab them from their websites? (I could try to ask them for their logos, but that might take forever, and I doubt they'd complain. I can ask them after the fact).
I found some updates for those sites:
The new URL for Genocide Watch is genocidewatch.net
The new URL for the Holocaust Museum is http://www.ushmm.org
The Republic of Armenia - Armenian Genocide Museum & Institute site is now genocide-museum.am
The Model Curriculum site (whose title should be changed to California Model Curriculum...) is now: http://www.cde.ca.gov/ci/hs/im/documents/modelcurrichrgenoc.pdf

**Comment by SourenP** [comment]
Updated the site urls

This template is the same as the one for videos and books. 
This means that you guys (admins) can set an image. I set a placeholder for genocidewatch, just so you know how it looks. 
This also means that once we fix the videos and books titles to look better, this will change also.

**Comment by Hasmig** [comment]
OK.

**Comment by copacetic** [comment]
Closing.
