### ISSUE TITLE
Change style of book/video categories

### ISSUE THREAD

**Issue by SourenP** [GenEdProject/TeachGenocideSite#75]
Hayg:
I like that the dividers go all the way across. I think the section headers should have a more significant font styling though. And the dividers could maybe benefit from being a bit bolder. We should also take advantage of 'Read more' for each item. Only a one or two line summary should be visible on the list page.
  
Hasmig:
I agree that the section headers should have strong styling and the dividers bolder. On the books page, the order of sections should follow that of our current site, as I mentioned earlier. On the Videos page, the headers should specify what type of videos in each section. Also, as I had mentioned early on, we'd like to embed a number of our YouTube videos on that page, or at least have a prominent announcement there that teachers can access short, classroom-ready videos on our YouTube page. But since there are also other non-classroom videos on our YT page, I'd prefer to embed a few of the key videos, and indicate that there are also others on YT.

**Comment by copacetic** [comment]
"I like that the dividers go all the way across. I think the section headers should have a more significant font styling though. And the dividers could maybe benefit from being a bit bolder"

Then we agree haha :P
