### ISSUE TITLE
Homepage video box

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#79]
I noticed that the video in on the homepage is not displaying with the correct size/ratio. Can we fix that? Do we need to change the shape of the box so that the video will fit? (as well as whatever other news item we switch it out with periodically.)

For the list of Teaching Resources on the homepage, can you match it with the ones on Melani's last mock-up, which I'll send you via email (I can't attach a PDF here)?

"Denial" doesn't need to be one of the items in that list. It should just be one of the pages in the Background drop down list on top.

**Comment by GenEdProject** [comment]
@Hasmig it looks fine for us... can you attach a screenshot of what you are experiencing? Our tiny laptop screens may be hiding the issue.

**Comment by Hasmig** [comment]
Attached is a screen shot of the homepage, seen from my 27 in (?) Mac at work, so you can see what the video box looks like.

Also, I'm assuming there's a white box around the logo, because that's part of the image I sent you, right?  Yesterday, I emailed Arsineh again, asking her to send us the InDesign files for her artwork, so we can separate out the design elements and use them on the website. So, I'm hoping I'll get those soon. 

Melani is working on new colors that might be more complementary with the new green of the logo and other materials.
![screen shot 2015-06-17 at 8 39 00 am](https://cloud.githubusercontent.com/assets/11155569/8211896/b672bde6-14cd-11e5-8c8f-d6234f447b88.png)

**Comment by SourenP** [comment]
We're still a bit confused as to what's wrong with the video box. 
If you play it, the video looks fine and fullscreen works. 

In fact, that box has a static size. We can set it to whatever we want but depending on the most recent press release, the content in it will change. (video will have black sides, text will cut off with a "read more" button"

Yeah the logo just needs to be replaced with a png that has an invisible background.

Can't wait to see what the new colors look like!

**Comment by SourenP** [comment]
Put a large video on the homepage for now.
Doesn't look bad.
People will definitely notice the stuff under it when they scroll down to have the video in the center of their screen.
