### ISSUE TITLE
Alignment issues

### ISSUE THREAD

**Issue by copacetic** [GenEdProject/TeachGenocideSite#81]
* Social media icons are too low in the header
* In Chrome (linux), the search box droops and is thus misaligned with the submit button
* In Firefox(linux) and reportedly Safari, the Register button overlaps with the search box.

**Comment by GenEdProject** [comment]
@copacetic fixed the social media icons issue. Also fixed the search box drooping and some slight padding issues. The only task left is the Register button overlap.
